//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.WCF.CTeRecepcaoEvento
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento", ConfigurationName="Sefaz.WCF.CTeRecepcaoEvento.CteRecepcaoEventoSoap12")]
    internal interface CteRecepcaoEventoSoap12
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento/cteRecepcaoEvento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Sefaz.WCF.CTeRecepcaoEvento.cteRecepcaoEventoResponse> cteRecepcaoEventoAsync(Sefaz.WCF.CTeRecepcaoEvento.cteRecepcaoEventoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento")]
    public partial class cteCabecMsg
    {
        
        private string cUFField;
        
        private string versaoDadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cUF
        {
            get
            {
                return this.cUFField;
            }
            set
            {
                this.cUFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string versaoDados
        {
            get
            {
                return this.versaoDadosField;
            }
            set
            {
                this.versaoDadosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class cteRecepcaoEventoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento")]
        public Sefaz.WCF.CTeRecepcaoEvento.cteCabecMsg cteCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento", Order=0)]
        public System.Xml.XmlNode cteDadosMsg;
        
        public cteRecepcaoEventoRequest()
        {
        }
        
        public cteRecepcaoEventoRequest(Sefaz.WCF.CTeRecepcaoEvento.cteCabecMsg cteCabecMsg, System.Xml.XmlNode cteDadosMsg)
        {
            this.cteCabecMsg = cteCabecMsg;
            this.cteDadosMsg = cteDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class cteRecepcaoEventoResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento")]
        public Sefaz.WCF.CTeRecepcaoEvento.cteCabecMsg cteCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento", Order=0)]
        public System.Xml.XmlNode cteRecepcaoEventoResult;
        
        public cteRecepcaoEventoResponse()
        {
        }
        
        public cteRecepcaoEventoResponse(Sefaz.WCF.CTeRecepcaoEvento.cteCabecMsg cteCabecMsg, System.Xml.XmlNode cteRecepcaoEventoResult)
        {
            this.cteCabecMsg = cteCabecMsg;
            this.cteRecepcaoEventoResult = cteRecepcaoEventoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface CteRecepcaoEventoSoap12Channel : Sefaz.WCF.CTeRecepcaoEvento.CteRecepcaoEventoSoap12, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class CteRecepcaoEventoSoap12Client : System.ServiceModel.ClientBase<Sefaz.WCF.CTeRecepcaoEvento.CteRecepcaoEventoSoap12>, Sefaz.WCF.CTeRecepcaoEvento.CteRecepcaoEventoSoap12
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CteRecepcaoEventoSoap12Client() : 
                base(CteRecepcaoEventoSoap12Client.GetDefaultBinding(), CteRecepcaoEventoSoap12Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CteRecepcaoEventoSoap12.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CteRecepcaoEventoSoap12Client(EndpointConfiguration endpointConfiguration) : 
                base(CteRecepcaoEventoSoap12Client.GetBindingForEndpoint(endpointConfiguration), CteRecepcaoEventoSoap12Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CteRecepcaoEventoSoap12Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CteRecepcaoEventoSoap12Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CteRecepcaoEventoSoap12Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CteRecepcaoEventoSoap12Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CteRecepcaoEventoSoap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sefaz.WCF.CTeRecepcaoEvento.cteRecepcaoEventoResponse> Sefaz.WCF.CTeRecepcaoEvento.CteRecepcaoEventoSoap12.cteRecepcaoEventoAsync(Sefaz.WCF.CTeRecepcaoEvento.cteRecepcaoEventoRequest request)
        {
            return base.Channel.cteRecepcaoEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sefaz.WCF.CTeRecepcaoEvento.cteRecepcaoEventoResponse> cteRecepcaoEventoAsync(Sefaz.WCF.CTeRecepcaoEvento.cteCabecMsg cteCabecMsg, System.Xml.XmlNode cteDadosMsg)
        {
            Sefaz.WCF.CTeRecepcaoEvento.cteRecepcaoEventoRequest inValue = new Sefaz.WCF.CTeRecepcaoEvento.cteRecepcaoEventoRequest();
            inValue.cteCabecMsg = cteCabecMsg;
            inValue.cteDadosMsg = cteDadosMsg;
            return ((Sefaz.WCF.CTeRecepcaoEvento.CteRecepcaoEventoSoap12)(this)).cteRecepcaoEventoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CteRecepcaoEventoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CteRecepcaoEventoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CteRecepcaoEventoSoap12Client.GetBindingForEndpoint(EndpointConfiguration.CteRecepcaoEventoSoap12);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CteRecepcaoEventoSoap12Client.GetEndpointAddress(EndpointConfiguration.CteRecepcaoEventoSoap12);
        }
        
        public enum EndpointConfiguration
        {
            
            CteRecepcaoEventoSoap12,
        }
    }
}
