//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.WCF.CTeDistribuicaoDFe
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", ConfigurationName="Sefaz.WCF.CTeDistribuicaoDFe.CTeDistribuicaoDFeSoap")]
    internal interface CTeDistribuicaoDFeSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe/cteDistDFeInteresse", ReplyAction="*")]
        System.Threading.Tasks.Task<Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseResponse> cteDistDFeInteresseAsync(Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class cteDistDFeInteresseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cteDistDFeInteresse", Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", Order=0)]
        public Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseRequestBody Body;
        
        public cteDistDFeInteresseRequest()
        {
        }
        
        public cteDistDFeInteresseRequest(Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe")]
    internal partial class cteDistDFeInteresseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement cteDadosMsg;
        
        public cteDistDFeInteresseRequestBody()
        {
        }
        
        public cteDistDFeInteresseRequestBody(System.Xml.XmlElement cteDadosMsg)
        {
            this.cteDadosMsg = cteDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class cteDistDFeInteresseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cteDistDFeInteresseResponse", Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", Order=0)]
        public Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseResponseBody Body;
        
        public cteDistDFeInteresseResponse()
        {
        }
        
        public cteDistDFeInteresseResponse(Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe")]
    internal partial class cteDistDFeInteresseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement cteDistDFeInteresseResult;
        
        public cteDistDFeInteresseResponseBody()
        {
        }
        
        public cteDistDFeInteresseResponseBody(System.Xml.XmlElement cteDistDFeInteresseResult)
        {
            this.cteDistDFeInteresseResult = cteDistDFeInteresseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface CTeDistribuicaoDFeSoapChannel : Sefaz.WCF.CTeDistribuicaoDFe.CTeDistribuicaoDFeSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class CTeDistribuicaoDFeSoapClient : System.ServiceModel.ClientBase<Sefaz.WCF.CTeDistribuicaoDFe.CTeDistribuicaoDFeSoap>, Sefaz.WCF.CTeDistribuicaoDFe.CTeDistribuicaoDFeSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CTeDistribuicaoDFeSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CTeDistribuicaoDFeSoapClient.GetBindingForEndpoint(endpointConfiguration), CTeDistribuicaoDFeSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CTeDistribuicaoDFeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CTeDistribuicaoDFeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CTeDistribuicaoDFeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CTeDistribuicaoDFeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CTeDistribuicaoDFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseResponse> Sefaz.WCF.CTeDistribuicaoDFe.CTeDistribuicaoDFeSoap.cteDistDFeInteresseAsync(Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseRequest request)
        {
            return base.Channel.cteDistDFeInteresseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseResponse> cteDistDFeInteresseAsync(System.Xml.XmlElement cteDadosMsg)
        {
            Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseRequest inValue = new Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseRequest();
            inValue.Body = new Sefaz.WCF.CTeDistribuicaoDFe.cteDistDFeInteresseRequestBody();
            inValue.Body.cteDadosMsg = cteDadosMsg;
            return ((Sefaz.WCF.CTeDistribuicaoDFe.CTeDistribuicaoDFeSoap)(this)).cteDistDFeInteresseAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CTeDistribuicaoDFeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CTeDistribuicaoDFeSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CTeDistribuicaoDFeSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www1.cte.fazenda.gov.br/CTeDistribuicaoDFe/CTeDistribuicaoDFe.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CTeDistribuicaoDFeSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www1.cte.fazenda.gov.br/CTeDistribuicaoDFe/CTeDistribuicaoDFe.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CTeDistribuicaoDFeSoap,
            
            CTeDistribuicaoDFeSoap12,
        }
    }
}
