//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefaz.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WsCteRecepcaoEvento {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WsCteRecepcaoEvento() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sefaz.Core.WsCteRecepcaoEvento", typeof(WsCteRecepcaoEvento).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _26 {
            get {
                return ResourceManager.GetString("26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _27 {
            get {
                return ResourceManager.GetString("27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _28 {
            get {
                return ResourceManager.GetString("28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _29 {
            get {
                return ResourceManager.GetString("29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.fazenda.mg.gov.br/cte/services/RecepcaoEvento.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _33 {
            get {
                return ResourceManager.GetString("33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcaoEvento.asmx.
        /// </summary>
        internal static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.fazenda.pr.gov.br/cte/CteRecepcaoEvento?wsdl.
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _43 {
            get {
                return ResourceManager.GetString("43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://producao.cte.ms.gov.br/ws/CteRecepcaoEvento.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.sefaz.mt.gov.br/ctews2/services/CteRecepcaoEvento?wsdl.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx.
        /// </summary>
        internal static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
    }
}
