name: Atualizar pacote no Nuget.org

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Configurar .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Contruir e Criar Pacote
      run: dotnet build --configuration Release

    - name: Testar
      run: dotnet test
    
    - name: Publicar
      run: dotnet nuget push ./src/Sefaz.Core/bin/Release/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
